// src/mcp/tools/_generated.ts — GENERATED. Do not hand-edit.
// Generated by: pnpm gen:schemas (scripts/gen-schemas.ts)
// Source of truth: spec/mcp-tools.yaml

import { z } from 'zod'

export type Toolset = 'cli' | 'workflow' | 'read' | 'admin'

// ── clawops_status ──────────────────────────────────────────────────────────

export const clawops_statusSchema = z.object({
  stackName: z.string().optional().describe("Stack name. Defaults to active stack from config."),
})

export const clawops_statusDescription = "Get what is deployed for a clawops-managed stack: public IP, gateway URL,\nSSH user, or that nothing is deployed yet. Reads stack outputs; does not\ncontact the host.\n\nUse when: the user asks what exists for a stack, or where to reach it.\n\nDo NOT use when: the user asks whether the gateway is actually WORKING —\nthat needs the host, so use clawops_doctor. Also not for live logs (use\nclawops_logs_tail) or config values (use clawops_config_get)."

export const clawops_statusAnnotations = {
  title: "Get Stack Status",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type StatusInput = z.infer<typeof clawops_statusSchema>

// ── clawops_doctor ──────────────────────────────────────────────────────────

export const clawops_doctorSchema = z.object({
  stackName: z.string().optional().describe("Stack to include remote checks for. Without it, only the local machine is\nchecked — no SSH connection is made.\n"),
  failuresOnly: z.boolean().optional().default(false).describe("Return only failing and warning checks. Passing checks are counted, not listed."),
})

export const clawops_doctorDescription = "Run clawops's diagnostics and return the report: Node and Pulumi runtime, config,\nSSH key and known_hosts, cloud credentials per configured provider, and the\nsupported OpenClaw range. With stackName, also contacts the host for container\nstate, the deployed OpenClaw version, a real gateway health probe, whether the\nport is published to the internet, disk usage on the state directory, log\nrotation, and hardening drift.\n\nUse when: something is not working and you do not yet know what; before any\ndeploy, upgrade or migration; or to find out which OpenClaw version a gateway is\nactually running.\n\nDo NOT use when: you already know the problem and want to fix it. This tool only\nreports — it changes nothing, and never runs `openclaw doctor --fix`. No tool\nrepairs a gateway: `clawops gateway update` is CLI-only, so tell the user to run\nit themselves, after `clawops backup create`.\n\nEvery check carries a status: fail (something is wrong that clawops can name),\nwarn (worth knowing, not broken), info (did not apply). `ok` is false only when\nsomething failed — a fresh machine with no stacks is full of warnings and healthy."

export const clawops_doctorAnnotations = {
  title: "Run Diagnostics",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type DoctorInput = z.infer<typeof clawops_doctorSchema>

// ── clawops_logs_tail ───────────────────────────────────────────────────────

export const clawops_logs_tailSchema = z.object({
  stackName: z.string().optional().describe("Which stack's gateway to read. Omitted = the default stack in ~/.clawops/config.json"),
  tailLines: z.number().int().optional().default(100).describe("How many of the most recent lines to return. Keep it small; output is trimmed to 8KB regardless"),
  sinceMin: z.number().int().optional().describe("Lines since N minutes ago"),
})

export const clawops_logs_tailDescription = "Tail recent gateway logs from a clawops-managed instance.\n\nUse when: the user wants to investigate recent activity or errors, or\nasks \"what's been happening\" on the gateway.\n\nDo NOT use when: the user wants real-time streaming logs (those are not\nwell-suited to tool calls; suggest the user run `clawops logs -f` directly\nin their terminal). Do NOT use for instance-level system logs: no tool runs\narbitrary remote commands, so tell the user to run `clawops ssh --command\n'journalctl ...'` themselves."

export const clawops_logs_tailAnnotations = {
  title: "Tail Gateway Logs",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type LogsTailInput = z.infer<typeof clawops_logs_tailSchema>

// ── clawops_monitor ─────────────────────────────────────────────────────────

export const clawops_monitorSchema = z.object({
  stackName: z.string().optional().describe("Stack name. Defaults to active stack."),
  tailLines: z.number().int().optional().default(5).describe("Log lines to include in snapshot."),
})

export const clawops_monitorDescription = "Take a live snapshot of a running clawops stack: gateway health, container\nstatus, resource usage (CPU, memory, disk), and recent log lines.\n\nUse when: the user wants to know if the gateway is running, how much\nmemory or CPU it is using, what recent log activity looks like, or\nwants a quick health overview richer than clawops_status.\n\nDo NOT use when: the user wants real-time streaming logs (use\nclawops_logs_tail or suggest `clawops logs -f`). Do NOT use for\nconfiguration queries (use clawops_config_get)."

export const clawops_monitorAnnotations = {
  title: "Monitor Stack Health",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type MonitorInput = z.infer<typeof clawops_monitorSchema>

// ── clawops_stacks_list ─────────────────────────────────────────────────────

export const clawops_stacks_listSchema = z.object({})

export const clawops_stacks_listDescription = "List all clawops-managed stacks across all configured providers.\n\nUse when: the user wants an overview of their deployments, asks \"what\nstacks do I have\", or wants to compare stacks before an operation.\n\nDo NOT use when: the user named a specific stack — use clawops_status\ndirectly with that name."

export const clawops_stacks_listAnnotations = {
  title: "List Stacks",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: false,
  toolsets: ["admin","read"] as const,
} as const

export type StacksListInput = z.infer<typeof clawops_stacks_listSchema>

// ── clawops_config_get ──────────────────────────────────────────────────────

export const clawops_config_getSchema = z.object({
  stackName: z.string().optional().describe("Which stack's gateway config to read. Omitted = the default stack in ~/.clawops/config.json"),
  key: z.string().optional().describe("Dot-path config key, e.g., gateway.auth.mode. Omit to dump the full config."),
})

export const clawops_config_getDescription = "Read a configuration value from the remote OpenClaw gateway.\n\nUse when: the user wants to inspect current OpenClaw config (e.g., which\nmodel provider is active, which channels are enabled).\n\nDo NOT use when: the user wants to change the config — use\nclawops_config_set instead."

export const clawops_config_getAnnotations = {
  title: "Get OpenClaw Config Value",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type ConfigGetInput = z.infer<typeof clawops_config_getSchema>

// ── clawops_agents_list ─────────────────────────────────────────────────────

export const clawops_agents_listSchema = z.object({
  stackName: z.string().optional().describe("Which stack's agents to list. Omitted = the default stack in ~/.clawops/config.json"),
})

export const clawops_agents_listDescription = "List agents currently registered on the remote OpenClaw gateway.\n\nUse when: the user wants to see which agents are running, debug agent\nrouting, or count active workspaces.\n\nDo NOT use when: the user wants one agent's activity — that is clawops_agents_logs."

export const clawops_agents_listAnnotations = {
  title: "List OpenClaw Agents",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type AgentsListInput = z.infer<typeof clawops_agents_listSchema>

// ── clawops_agents_logs ─────────────────────────────────────────────────────

export const clawops_agents_logsSchema = z.object({
  stackName: z.string().optional().describe("Which stack the agent runs on. Omitted = the default stack in ~/.clawops/config.json"),
  name: z.string().describe("The agent's name, as clawops_agents_list reports it"),
  limit: z.number().int().optional().default(50).describe("Maximum activity records to return. Omitted = 50"),
  cursor: z.string().optional().describe("The cursor a previous call returned, to continue from where it stopped. Omitted = the most recent records"),
})

export const clawops_agents_logsDescription = "One agent's recent activity, read from the gateway's audit log, newest last.\nPaginated: pass the returned cursor to continue.\n\nUse when: the user asks what a specific agent did, or why it behaved as it did.\n\nDo NOT use when: the user wants the gateway's own log stream — that is\nclawops_logs_tail. Do NOT use to find agent names — that is clawops_agents_list."

export const clawops_agents_logsAnnotations = {
  title: "Read One Agent's Activity",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type AgentsLogsInput = z.infer<typeof clawops_agents_logsSchema>

// ── clawops_gateway_status ──────────────────────────────────────────────────

export const clawops_gateway_statusSchema = z.object({
  stackName: z.string().optional().describe("Which stack's gateway to inspect. Omitted = the default stack in ~/.clawops/config.json"),
})

export const clawops_gateway_statusDescription = "Whether the OpenClaw gateway container is running, when it started, and which image it\nruns, as docker reports it on the host.\n\nUse when: the user asks whether the gateway is up or which OpenClaw version is deployed.\n\nDo NOT use when: the user wants a full health check — clawops_doctor probes the gateway\nitself rather than the container. Do NOT use to change anything; this only reads."

export const clawops_gateway_statusAnnotations = {
  title: "Gateway Container Status",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type GatewayStatusInput = z.infer<typeof clawops_gateway_statusSchema>

// ── clawops_secret_list ─────────────────────────────────────────────────────

export const clawops_secret_listSchema = z.object({})

export const clawops_secret_listDescription = "List the secrets clawops stores locally, by name and status. Never returns a value.\n\nUse when: the user asks which secrets are set, or before a deploy that references one.\n\nDo NOT use when: the user wants to set or rotate a secret. No tool does that, because the\nvalue would pass through the conversation (R6): ask the user to run\n`clawops secret set <NAME>` or `clawops secret rotate <NAME>` in a terminal."

export const clawops_secret_listAnnotations = {
  title: "List Stored Secrets",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: false,
  toolsets: ["cli","read"] as const,
} as const

export type SecretListInput = z.infer<typeof clawops_secret_listSchema>

// ── clawops_secret_audit ────────────────────────────────────────────────────

export const clawops_secret_auditSchema = z.object({})

export const clawops_secret_auditDescription = "Report secrets that stacks reference but clawops does not have, and `$secret:` references\nthat cannot be resolved. Never returns a value.\n\nUse when: a deploy or config change fails on a missing secret, or before applying a plan\nwhose config references secrets.\n\nDo NOT use when: the user wants to set the missing secret — ask them to run\n`clawops secret set <NAME>` in a terminal; no tool takes a secret value (R6)."

export const clawops_secret_auditAnnotations = {
  title: "Audit Secret References",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: false,
  toolsets: ["cli","read"] as const,
} as const

export type SecretAuditInput = z.infer<typeof clawops_secret_auditSchema>

// ── clawops_up ──────────────────────────────────────────────────────────────

export const clawops_upSchema = z.object({
  stackName: z.string().optional().describe("Name for the stack to provision, and the name every later command refers to it by. Omitted = the default stack in ~/.clawops/config.json"),
  provider: z.enum(['aws', 'gcp', 'azure', 'local']).optional().describe("Defaults to provider configured for this stack"),
  region: z.string().optional().describe("Cloud region to deploy into, in the provider's own spelling (us-east-1, us-central1, eastus). Omitted = the region recorded for the stack"),
  instanceType: z.string().optional().default("small").describe("A clawops size (micro|small|medium|large|gpu) or a provider-native machine type.\nNot an enum: Azure offers SKU families per subscription, and an account offered\nnone of the five sizes clawops names would otherwise have no way to deploy.\n"),
  sshCidr: z.string().optional().describe("CIDR(s) allowed to reach SSH, comma-separated, or 'auto' for the caller's own\naddress. Omitted means none, and nothing will be able to connect — including\nevery clawops day-two command.\n"),
  gatewayCidr: z.string().optional().describe("CIDR(s) allowed to reach the gateway port. Requires publishGateway=all."),
  publishGateway: z.enum(['loopback', 'all']).optional().describe("Which interface the gateway binds. 'all' serves plaintext HTTP."),
  openclawVersion: z.string().optional().describe("semver or 'stable'/'dev'"),
  dryRun: z.boolean().optional().default(false).describe("Show what would be created and change nothing. Use this first when the user has not yet approved a spend"),
})

export const clawops_upDescription = "Provision and deploy a clawops stack. Idempotent — re-running with no spec\nchange produces no diff. Long-running (median 3min, p99 8min) so emits\nprogress notifications per R12.\n\nUse when: the user explicitly asks to deploy, provision, create, or \"spin\nup\" a stack. Always after the user has reviewed a plan\n(clawops_plan first when in doubt).\n\nDo NOT use when: the user has not yet generated a plan and is in\nexploratory/discovery mode — use clawops_plan first. Do NOT use for an\nexisting stack you only need to update; refresh first."

export const clawops_upAnnotations = {
  title: "Provision and Deploy Stack",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type UpInput = z.infer<typeof clawops_upSchema>

// ── clawops_destroy ─────────────────────────────────────────────────────────

export const clawops_destroySchema = z.object({
  stackName: z.string().describe("The stack to destroy. Required, and worth repeating back to the user before calling: this deletes every resource it provisioned"),
  yes: z.boolean().optional().default(false).describe("Skip elicitation; CI/scripted use only"),
})

export const clawops_destroyDescription = "Destroy a clawops stack. Removes ALL provisioned resources. Triggers\nelicitation confirmation showing the resource diff before execution\n(R19). Cannot be undone.\n\nUse when: the user explicitly asks to destroy, tear down, delete, or\nremove a stack. Always confirm the stack name.\n\nDo NOT use when: the user wants to stop the gateway temporarily — that is not\na destroy, and no tool stops a gateway; clawops_gateway_restart is the only\ngateway tool. Do NOT use when in doubt about which stack; list first with\nclawops_stacks_list."

export const clawops_destroyAnnotations = {
  title: "Destroy Stack (DESTRUCTIVE)",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type DestroyInput = z.infer<typeof clawops_destroySchema>

// ── clawops_apply ───────────────────────────────────────────────────────────

export const clawops_applySchema = z.object({
  planPath: z.string().describe("Absolute path to plan JSON (R7)"),
  yes: z.boolean().optional().default(false).describe("Skip the confirmation and apply immediately. Only when the user has already approved this specific plan"),
})

export const clawops_applyDescription = "Apply a previously-generated Maker plan (deploy-plan.schema.json).\nDeterministic — the plan describes exactly what will be created.\n\nUse when: the user has a plan file path and wants to apply it. This is\nthe agent-friendly path for any deploy/destroy operation.\n\nDo NOT use when: there's no plan file — generate one first with\nclawops_plan."

export const clawops_applyAnnotations = {
  title: "Apply Maker Plan",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: false,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type ApplyInput = z.infer<typeof clawops_applySchema>

// ── clawops_plan ────────────────────────────────────────────────────────────

export const clawops_planSchema = z.object({
  stackName: z.string().optional().describe("Which stack the plan is for. Omitted = the default stack in ~/.clawops/config.json"),
  provider: z.enum(['aws', 'gcp', 'azure', 'local']).optional().describe("Cloud to plan against. Omitted = the provider recorded for the stack. 'local' has no plan/apply path and is refused"),
  region: z.string().optional().describe("Cloud region, in the provider's own spelling (us-east-1, us-central1, eastus). Omitted = the region recorded for the stack"),
  instanceType: z.string().optional().describe("A clawops alias (micro|small|medium|large|gpu) or a machine type the cloud names itself, e.g. t3.small"),
  openclawVersion: z.string().optional().describe("semver, or 'stable'/'dev'"),
  sshCidr: z.string().optional().describe("CIDR(s) allowed to reach SSH, comma-separated, or 'auto' for this machine. Omitted = none, and nothing will be able to connect"),
  gatewayCidr: z.string().optional().describe("CIDR(s) allowed to reach the gateway port, or 'auto'. Requires publishGateway=all"),
  publishGateway: z.enum(['loopback', 'all']).optional().describe("Which interface the gateway binds. loopback (default) keeps it off the network"),
  privateOnly: z.boolean().optional().describe("Close public SSH and gateway access; reach the stack over its tailnet. Requires a verified tailnet address (clawops_harden with tailscale), and refuses unless that address answers SSH now"),
  outPath: z.string().optional().describe("Absolute path to write plan; if omitted, plan returned inline"),
})

export const clawops_planDescription = "Generate a Maker deploy plan (does NOT apply). Plan is JSON conforming to\ndeploy-plan.schema.json — review before applying.\n\nUse when: the user wants to see what would be created before committing,\nor you (the agent) need a reviewable artifact for the user to approve.\n\nDo NOT use when: the user has explicitly asked to deploy and you already\nhave their approval — go directly to clawops_up."

export const clawops_planAnnotations = {
  title: "Generate Deploy Plan",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type PlanInput = z.infer<typeof clawops_planSchema>

// ── clawops_config_set ──────────────────────────────────────────────────────

export const clawops_config_setSchema = z.object({
  stackName: z.string().optional().describe("Which stack's gateway config to write. Omitted = the default stack in ~/.clawops/config.json"),
  key: z.string().describe("Dotted path into the gateway config, e.g. models.provider or channels.slack.enabled"),
  value: z.string().describe("Stringified; JSON for complex values"),
  restart: z.boolean().optional().default(false).describe("Restart the gateway so the change takes effect. Without it the value is written and the running gateway keeps the old one"),
})

export const clawops_config_setDescription = "Set a configuration value on the remote OpenClaw gateway. Optionally\nrestarts the gateway after.\n\nUse when: the user wants to change OpenClaw configuration (model\nprovider, channel auth, gateway port).\n\nDo NOT use when: the user is reading config — use clawops_config_get.\nDo NOT bulk-edit; one key at a time so changes are auditable (R21)."

export const clawops_config_setAnnotations = {
  title: "Set OpenClaw Config Value",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type ConfigSetInput = z.infer<typeof clawops_config_setSchema>

// ── clawops_config_unset ────────────────────────────────────────────────────

export const clawops_config_unsetSchema = z.object({
  stackName: z.string().optional().describe("Which stack's gateway config to write. Omitted = the default stack in ~/.clawops/config.json"),
  key: z.string().describe("Dot-path config key to remove"),
  restart: z.boolean().optional().default(false).describe("Restart the gateway so the removal takes effect. Without it the key is removed and the running gateway keeps the old value"),
})

export const clawops_config_unsetDescription = "Remove a configuration key from the remote OpenClaw gateway config, reverting\nit to the OpenClaw default.\n\nUse when: the user wants to delete a config key entirely (e.g., remove a\nchannel, clear an override).\n\nDo NOT use when: the user wants to set the key to a new value — use\nclawops_config_set instead."

export const clawops_config_unsetAnnotations = {
  title: "Unset OpenClaw Config Key",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type ConfigUnsetInput = z.infer<typeof clawops_config_unsetSchema>

// ── clawops_config_validate ─────────────────────────────────────────────────

export const clawops_config_validateSchema = z.object({
  stackName: z.string().optional().describe("Which stack's deployed config to validate. Omitted = the default stack in ~/.clawops/config.json"),
})

export const clawops_config_validateDescription = "Validate the remote OpenClaw gateway config against the known schema. Checks\nfor structural errors (wrong types, unknown top-level keys) that would cause\nOpenClaw to fail on startup.\n\nUse when: the user wants to verify config before restarting the gateway, or\nafter editing openclaw.json manually.\n\nDo NOT use when: the user wants to change config — use clawops_config_set."

export const clawops_config_validateAnnotations = {
  title: "Validate OpenClaw Config",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli","read"] as const,
} as const

export type ConfigValidateInput = z.infer<typeof clawops_config_validateSchema>

// ── clawops_gateway_restart ─────────────────────────────────────────────────

export const clawops_gateway_restartSchema = z.object({
  stackName: z.string().optional().describe("Which stack's gateway to restart. Omitted = the default stack in ~/.clawops/config.json"),
})

export const clawops_gateway_restartDescription = "Restart the OpenClaw gateway daemon on the remote instance.\n\nUse when: a gateway-wide config change requires reload, or the gateway is\nreported as unresponsive.\n\nNote: OpenClaw 2.0 removed per-agent restart; `gateway restart` is the only\nrestart it offers, and it affects every agent on the host. Brief downtime (~10s)."

export const clawops_gateway_restartAnnotations = {
  title: "Restart Gateway Daemon",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type GatewayRestartInput = z.infer<typeof clawops_gateway_restartSchema>

// ── clawops_gateway_update ──────────────────────────────────────────────────

export const clawops_gateway_updateSchema = z.object({
  stackName: z.string().optional().describe("Which stack's gateway to update. Omitted = the default stack in ~/.clawops/config.json"),
  version: z.string().describe("A concrete OpenClaw version to move to, e.g. 2026.9.2. Moving tags are refused"),
  yes: z.boolean().optional().default(false).describe("Skip the confirmation. Only when the user has already approved this specific update"),
})

export const clawops_gateway_updateDescription = "Move the gateway to a different OpenClaw version: pull the image and restart the gateway\non it. Every agent on the host restarts with it.\n\nUse when: the user asks to upgrade or downgrade OpenClaw on a running stack, naming a\nversion.\n\nDo NOT use when: the user has not named a concrete version — moving tags such as\n`latest` are refused, as the CLI refuses them. Do NOT use without a backup the user can\nreturn to: suggest clawops_backup_create first."

export const clawops_gateway_updateAnnotations = {
  title: "Update OpenClaw Version",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type GatewayUpdateInput = z.infer<typeof clawops_gateway_updateSchema>

// ── clawops_backup_create ───────────────────────────────────────────────────

export const clawops_backup_createSchema = z.object({
  stackName: z.string().optional().describe("Which stack to back up. Omitted = the default stack in ~/.clawops/config.json"),
  out: z.string().optional().describe("Absolute local path to write the archive to. Omitted = a timestamped file under ~/.clawops/backups"),
})

export const clawops_backup_createDescription = "Take a backup of the gateway's state (config, database, sessions, transcripts and\ninstalled plugins) and download it to a local archive. Live state is not changed.\n\nUse when: the user asks for a backup, and before anything that replaces state: a\nversion update, a migration, a restore, or a plan that replaces the instance.\n\nDo NOT use when: the user wants to back up cloud infrastructure — Pulumi state and plans\ncover that, not this."

export const clawops_backup_createAnnotations = {
  title: "Back Up Gateway State",
  readOnlyHint: false,
  destructiveHint: false,
  idempotentHint: false,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type BackupCreateInput = z.infer<typeof clawops_backup_createSchema>

// ── clawops_backup_restore ──────────────────────────────────────────────────

export const clawops_backup_restoreSchema = z.object({
  stackName: z.string().optional().describe("Which stack to restore onto. Omitted = the default stack in ~/.clawops/config.json"),
  file: z.string().describe("Absolute local path to the backup archive, as clawops_backup_create wrote it"),
  activate: z.boolean().optional().default(false).describe("Put the restored state into service. Omitted = expand into a staging directory and touch nothing live"),
  yes: z.boolean().optional().default(false).describe("Skip the confirmation. Only when the user has already approved this specific restore"),
})

export const clawops_backup_restoreDescription = "Verify a backup archive and expand it on the host beside the live state, never over it.\nWith activate: true, also put it into service: stop the gateway, swap the restored state\nin (keeping the state it replaces), restart, and roll back if the gateway does not answer.\n\nUse when: the user asks to restore or recover from a backup, naming the archive.\n\nDo NOT use when: the gateway is merely unhealthy — clawops_workflow_recover diagnoses that\nwithout discarding state. Restoring is time travel: everything since the backup is lost,\nand channel credentials may need relinking."

export const clawops_backup_restoreAnnotations = {
  title: "Restore Gateway State (DESTRUCTIVE with activate)",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: false,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type BackupRestoreInput = z.infer<typeof clawops_backup_restoreSchema>

// ── clawops_migrate ─────────────────────────────────────────────────────────

export const clawops_migrateSchema = z.object({
  stackName: z.string().optional().describe("Which stack to migrate. Omitted = the default stack in ~/.clawops/config.json"),
  openclawVersion: z.string().optional().describe("The OpenClaw 2.x version to migrate to. Omitted = the version this clawops release defaults to"),
  yes: z.boolean().optional().default(false).describe("Skip the confirmation. Only when the user has already approved this migration"),
})

export const clawops_migrateDescription = "Move a deployment from OpenClaw 1.x onto the 2.0 runtime contract: state ownership,\nconfig, and the gateway's run command, in the order a real migration showed works.\n\nUse when: a stack still runs OpenClaw 1.x and the user wants it on 2.x. clawops_doctor\nand clawops_gateway_status say which line a stack runs.\n\nDo NOT use when: the stack is already on 2.x — use clawops_gateway_update to change\nversions within 2.x. Take a backup first with clawops_backup_create."

export const clawops_migrateAnnotations = {
  title: "Migrate 1.x to 2.0 (DESTRUCTIVE)",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: false,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type MigrateInput = z.infer<typeof clawops_migrateSchema>

// ── clawops_stacks_delete ───────────────────────────────────────────────────

export const clawops_stacks_deleteSchema = z.object({
  name: z.string().describe("The stack to remove from config, as clawops_stacks_list reports it"),
  force: z.boolean().optional().default(false).describe("Skip the safety checks: allow deleting the default stack, or one still deployed. Omitted = refuse both"),
  yes: z.boolean().optional().default(false).describe("Skip the confirmation. Only when the user has already approved this deletion"),
})

export const clawops_stacks_deleteDescription = "Remove a stack from ~/.clawops/config.json. This forgets the stack; it does not tear\ndown its infrastructure, and it refuses a stack that is still deployed unless forced.\n\nUse when: the user wants to stop tracking a stack whose resources are already gone.\n\nDo NOT use when: the user wants the infrastructure removed — that is clawops_destroy,\nfirst. Forcing the delete of a deployed stack leaves resources running and billing that\nclawops can no longer see."

export const clawops_stacks_deleteAnnotations = {
  title: "Forget a Stack (DESTRUCTIVE)",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: false,
  toolsets: ["admin"] as const,
} as const

export type StacksDeleteInput = z.infer<typeof clawops_stacks_deleteSchema>

// ── clawops_secret_delete ───────────────────────────────────────────────────

export const clawops_secret_deleteSchema = z.object({
  name: z.string().describe("The secret's name, as clawops_secret_list reports it"),
  yes: z.boolean().optional().default(false).describe("Skip the confirmation. Only when the user has already approved this deletion"),
})

export const clawops_secret_deleteDescription = "Delete a locally stored secret by name. Warns when a stack still references it.\n\nUse when: the user asks to remove a secret they no longer use.\n\nDo NOT use when: the user wants to replace a value — ask them to run\n`clawops secret rotate <NAME>`; no tool takes a secret value (R6)."

export const clawops_secret_deleteAnnotations = {
  title: "Delete a Stored Secret (DESTRUCTIVE)",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: false,
  toolsets: ["cli"] as const,
} as const

export type SecretDeleteInput = z.infer<typeof clawops_secret_deleteSchema>

// ── clawops_init ────────────────────────────────────────────────────────────

export const clawops_initSchema = z.object({
  provider: z.enum(['aws', 'gcp', 'azure', 'local']).describe("Which cloud this stack deploys to, or 'local' for a machine you already have"),
  stackName: z.string().optional().describe("Name for the stack, used by every later call. Omitted = \"default\""),
  stateUrl: z.string().optional().describe("Where Pulumi state lives, e.g. s3://bucket/clawops, gs://bucket/clawops, azblob://container. Omitted = clawops names one from the cloud account it can see, which needs credentials"),
  region: z.string().optional().describe("Cloud region in the provider's own spelling. Omitted = us-east-1 (aws), us-central1 (gcp), eastus (azure)"),
  host: z.string().optional().describe("[local only] Hostname or IP of the machine to manage. Required when provider is local"),
  sshUser: z.string().optional().describe("[local only] SSH login user. Omitted = root"),
  sshPort: z.number().int().optional().describe("[local only] SSH port. Omitted = 22"),
  force: z.boolean().optional().describe("Overwrite a stack that already exists. Refused without it, because replacing a state backend orphans the state it points at"),
})

export const clawops_initDescription = "Register a stack and write ~/.clawops/config.json: the provider, the state backend, the\nregion, and an SSH key pair generated if one is not already there. Nothing is provisioned\nand nothing is charged; this only creates local configuration.\n\nUse when: any other clawops tool reports that there is no config, or the user wants to add\na second stack alongside the ones they have. This is the first call on a machine that has\nnever run clawops — a fresh container, a new laptop, a sandbox.\n\nAdding a stack is additive and safe: existing stacks are kept. Overwriting one needs\nforce: true, because changing a state backend orphans the Pulumi state it points at — the\ninfrastructure stays up and clawops can no longer see or destroy it.\n\nFor aws, gcp and azure, stateUrl can be omitted and clawops names a bucket from the\naccount it can see; that needs cloud credentials in the environment, so in a sandbox pass\nstateUrl explicitly. The local provider needs host instead, and no cloud account at all.\n\nDo NOT use when: the user wants to deploy — that is clawops_up, after this. Credentials\nare never passed here: clawops reads them from the environment (R6)."

export const clawops_initAnnotations = {
  title: "Initialise clawops Config",
  readOnlyHint: false,
  destructiveHint: false,
  idempotentHint: false,
  openWorldHint: false,
  toolsets: ["cli"] as const,
} as const

export type InitInput = z.infer<typeof clawops_initSchema>

// ── clawops_harden ──────────────────────────────────────────────────────────

export const clawops_hardenSchema = z.object({
  stackName: z.string().optional().describe("Which stack to harden. Omitted = the default stack in ~/.clawops/config.json"),
  options: z.string().optional().describe("Comma-separated module IDs; default is every defaultOn module for the provider"),
  dryRun: z.boolean().optional().default(false).describe("Report the current state, change nothing"),
  tailscale: z.boolean().optional().default(false).describe("Join the tailnet, verify this machine reaches the host there, then use that address"),
  tailscaleRevert: z.boolean().optional().default(false).describe("Leave the tailnet and go back to the public address"),
  yes: z.boolean().optional().default(false).describe("Skip elicitation; CI/scripted use only"),
})

export const clawops_hardenDescription = "Apply security hardening to a deployed stack: SSH, UFW, fail2ban,\nunattended-upgrades, the Docker socket, and per-cloud checks. Optionally join\nthe stack to a Tailscale network and reach it there instead of over the public\ninternet.\n\nUse when: the user asks to harden, secure, or lock down a stack; asks what the\nhardening report says (with dryRun: true, which changes nothing); or asks to put\na stack on their tailnet.\n\ntailscale: true installs Tailscale, joins the tailnet as clawops-<stack>, and\nthen moves clawops onto that address — but only after opening an SSH session to\nit, against host keys pinned over the connection already trusted. If that fails,\nnothing is recorded and the public address stays in use. The auth key comes from\n`clawops secret set TAILSCALE_AUTH_KEY` and is never passed through this tool\n(R6).\n\ntailscaleRevert: true takes the host back off the tailnet, over its public\naddress. On a private-only stack it refuses and names the plan/apply commands\nthat reopen SSH first — relay them rather than trying to work around it.\n\nTo close the public ports afterwards, plan with privateOnly: true and apply that\nplan; this tool does not change firewall rules.\n\nDo NOT use when: the user wants to know whether a stack is healthy — that is\nclawops_doctor. Do NOT pass tailscale and tailscaleRevert together."

export const clawops_hardenAnnotations = {
  title: "Harden Stack",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["cli"] as const,
} as const

export type HardenInput = z.infer<typeof clawops_hardenSchema>

// ── clawops_workflow_deploy_app ─────────────────────────────────────────────

export const clawops_workflow_deploy_appSchema = z.object({
  provider: z.enum(['aws', 'gcp', 'azure', 'local']).describe("Cloud to deploy to. Omitted = the default provider in ~/.clawops/config.json"),
  region: z.string().optional().describe("Cloud region, in the provider's own spelling (us-east-1, us-central1, eastus). Omitted = the provider's default"),
  stackName: z.string().optional().default("default").describe("Name for the new stack. Omitted = the default stack name in ~/.clawops/config.json"),
  instanceType: z.enum(['micro', 'small', 'medium', 'large', 'gpu']).optional().default("small").describe("Machine size: a clawops alias (micro|small|medium|large|gpu) or a type the cloud names itself, e.g. t3.small"),
})

export const clawops_workflow_deploy_appDescription = "Single-tool workflow that takes a user from \"I want to deploy OpenClaw\nto <provider>\" to a verified, healthy gateway. Internally: plan → user\nconfirms (elicitation) → up → wait for healthy → return URL.\n\nUse when: the user expresses end-to-end deployment intent (\"deploy to\nAWS\", \"spin up an OpenClaw on GCP for me\").\n\nDo NOT use when: the user is mid-deployment and only needs one step\n(e.g., they already have a plan; use clawops_apply). Do NOT use for\ndestroying or updating — separate workflows."

export const clawops_workflow_deploy_appAnnotations = {
  title: "Deploy OpenClaw (End-to-End Workflow)",
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["workflow"] as const,
} as const

export type WorkflowDeployAppInput = z.infer<typeof clawops_workflow_deploy_appSchema>

// ── clawops_workflow_recover ────────────────────────────────────────────────

export const clawops_workflow_recoverSchema = z.object({
  stackName: z.string().optional().describe("Which stack to diagnose. Omitted = the default stack in ~/.clawops/config.json"),
})

export const clawops_workflow_recoverDescription = "Diagnostic workflow for an unhealthy stack. Internally: status check →\ngateway logs → agent logs → systemd service status → produces a structured\ndiagnostic report with suggested remediation.\n\nUse when: the user reports any \"not working\" symptom and you don't know\nwhere to start. Best entry point for troubleshooting.\n\nDo NOT use when: the user has already identified the problem and asks for\na specific fix."

export const clawops_workflow_recoverAnnotations = {
  title: "Recover/Diagnose Stack",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
  toolsets: ["workflow","read"] as const,
} as const

export type WorkflowRecoverInput = z.infer<typeof clawops_workflow_recoverSchema>

// ── clawops_task_status ─────────────────────────────────────────────────────

export const clawops_task_statusSchema = z.object({
  taskId: z.string().describe("The taskId returned by a long-running tool such as clawops_up, clawops_apply or clawops_destroy"),
})

export const clawops_task_statusDescription = "Poll the status of a long-running clawops task (returned by clawops_up,\nclawops_destroy, clawops_apply, etc.). Per R12 streaming model.\n\nUse when: the user is waiting on a long-running deploy/destroy and wants\nprogress, OR you need to check whether a previously-started operation\nfinished.\n\nDo NOT use when: there is no active taskId — start the operation first."

export const clawops_task_statusAnnotations = {
  title: "Get Task Status",
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: false,
  toolsets: ["cli","read"] as const,
} as const

export type TaskStatusInput = z.infer<typeof clawops_task_statusSchema>

// ── TOOLSETS registry ─────────────────────────────────────────────────────────

export const TOOLSETS: Record<Toolset, string[]> = {
  cli: [
    'clawops_status',
    'clawops_doctor',
    'clawops_logs_tail',
    'clawops_monitor',
    'clawops_config_get',
    'clawops_agents_list',
    'clawops_agents_logs',
    'clawops_gateway_status',
    'clawops_secret_list',
    'clawops_secret_audit',
    'clawops_up',
    'clawops_destroy',
    'clawops_apply',
    'clawops_plan',
    'clawops_config_set',
    'clawops_config_unset',
    'clawops_config_validate',
    'clawops_gateway_restart',
    'clawops_gateway_update',
    'clawops_backup_create',
    'clawops_backup_restore',
    'clawops_migrate',
    'clawops_secret_delete',
    'clawops_init',
    'clawops_harden',
    'clawops_task_status',
  ],
  workflow: [
    'clawops_workflow_deploy_app',
    'clawops_workflow_recover',
  ],
  read: [
    'clawops_status',
    'clawops_doctor',
    'clawops_logs_tail',
    'clawops_monitor',
    'clawops_stacks_list',
    'clawops_config_get',
    'clawops_agents_list',
    'clawops_agents_logs',
    'clawops_gateway_status',
    'clawops_secret_list',
    'clawops_secret_audit',
    'clawops_plan',
    'clawops_config_validate',
    'clawops_workflow_recover',
    'clawops_task_status',
  ],
  admin: [
    'clawops_stacks_list',
    'clawops_stacks_delete',
  ],
}
