// src/providers/types.ts — GENERATED. Do not hand-edit.
// Generated by: pnpm gen:schemas (scripts/gen-schemas.ts)
// Source of truth: spec/providers.schema.json

/** Inline Pulumi program — a closure that creates resources when called. */
export type PulumiFn = () => Promise<Record<string, unknown> | void>

/** Lowercase provider id matching the schema enum. */
export type ProviderName = 'aws' | 'gcp' | 'azure' | 'local'

/** Normalised clawops instance-size alias. */
export type InstanceAlias = 'micro' | 'small' | 'medium' | 'large' | 'gpu'

/** How this provider's credentials are sourced (R6: never in tool args). */
export type CredentialSource = 'env' | 'cli-profile' | 'file' | 'instance-metadata'

/** Pulumi state backend URL scheme. */
export type StateBackendScheme = 's3' | 'gs' | 'azblob' | 'file'

export interface ConnectionInfo {
  host: string
  port: number
  user: string
  privateKeyPath: string
  knownHostsPath: string
}

export interface BaseStackOutputs {
  instanceId: string
  publicIp: string
  gatewayUrl: string
  sshHost: string
  sshPort: number
  sshUser: string
  region: string
  /** ISO-8601 timestamp */
  provisionedAt: string
}

export type StackOutputs = BaseStackOutputs & Record<string, unknown>

export interface ValidationResult {
  ok: boolean
  errors: string[]
}

/** Contract every cloud provider adapter must satisfy. Per R-meta-1. */
export interface ProviderAdapter {
  /** Lowercase provider id matching the schema enum. */
  readonly name: ProviderName

  /** Inline Pulumi program for this provider's stack. */
  readonly program: PulumiFn

  /** Extract connection details from a deployed stack's outputs. */
  getConnectionInfo(outputs: StackOutputs): ConnectionInfo

  /** Map an alias like "small" to the provider's native instance type. */
  normalizeInstanceType(alias: InstanceAlias): string

  /** Provider-default region if user didn't specify. */
  defaultRegion(): string

  /** State backend URL prefix for this provider. */
  stateBackendUrl(bucket: string): string

  /** Validate provider-specific config (env vars, profiles) at startup. */
  validateConfig(): Promise<ValidationResult>

  /**
   * Account-level setup this provider needs before anything can be provisioned.
   *
   * Not infrastructure: enabling an API or creating a state bucket happens outside the
   * Pulumi program, because the state backend has to exist before Pulumi can run at all.
   * Optional — a provider with nothing to check omits it.
   */
  preflight?(opts: PreflightOpts): Promise<PreflightCheck[]>
}

export interface PreflightOpts {
  /** Where the stack will be deployed, when that changes what must be enabled. */
  region?: string
  /** State backend bucket or container, when the check covers it. */
  bucket?: string
  /**
   * The machine size about to be deployed, when the caller knows it.
   *
   * Azure offers SKU families per subscription, so "is this size available here" can only be
   * answered about a specific size. Without this the check falls back to the provider's
   * default alias, which is right for a default deploy and wrong for anyone passing
   * --instance-type: a deployment using an available size would be reported as broken.
   */
  instanceType?: string
  signal?: AbortSignal
}

export interface PreflightCheck {
  /** Stable kebab-case id, e.g. "compute-api-enabled". */
  id: string
  /** What is being checked, in the operator's terms. */
  label: string
  ok: boolean
  /** Why it failed, and what it means — shown when ok is false. */
  detail?: string
  /**
   * Applies the fix. Absent when clawops cannot fix it: a missing permission or an unpaid
   * billing account is not clawops's to resolve, and pretending otherwise wastes a prompt.
   */
  fix?: () => Promise<void>
  /**
   * What the fix changes in the operator's cloud account.
   *
   * Shown in the prompt, and required alongside fix(): consent to 'fix it' is not consent to
   * something unnamed.
   */
  mutates?: string
}
