// src/providers/types.ts — GENERATED. Do not hand-edit.
// Generated by: pnpm gen:schemas (scripts/gen-schemas.ts)
// Source of truth: spec/providers.schema.json

/** Inline Pulumi program — a closure that creates resources when called. */
export type PulumiFn = () => Promise<Record<string, unknown> | void>

/** Lowercase provider id matching the schema enum. */
export type ProviderName = 'aws' | 'gcp' | 'azure' | 'local'

/** Normalised clawops instance-size alias. */
export type InstanceAlias = 'micro' | 'small' | 'medium' | 'large' | 'gpu'

/** How this provider's credentials are sourced (R6: never in tool args). */
export type CredentialSource = 'env' | 'cli-profile' | 'file' | 'instance-metadata'

/** Pulumi state backend URL scheme. */
export type StateBackendScheme = 's3' | 'gs' | 'azblob' | 'file'

export interface ConnectionInfo {
  host: string
  port: number
  user: string
  privateKeyPath: string
  knownHostsPath: string
}

export interface BaseStackOutputs {
  instanceId: string
  publicIp: string
  gatewayUrl: string
  sshHost: string
  sshPort: number
  sshUser: string
  region: string
  /** ISO-8601 timestamp */
  provisionedAt: string
}

export type StackOutputs = BaseStackOutputs & Record<string, unknown>

export interface ValidationResult {
  ok: boolean
  errors: string[]
}

/** Contract every cloud provider adapter must satisfy. Per R-meta-1. */
export interface ProviderAdapter {
  /** Lowercase provider id matching the schema enum. */
  readonly name: ProviderName

  /** Inline Pulumi program for this provider's stack. */
  readonly program: PulumiFn

  /** Extract connection details from a deployed stack's outputs. */
  getConnectionInfo(outputs: StackOutputs): ConnectionInfo

  /** Map an alias like "small" to the provider's native instance type. */
  normalizeInstanceType(alias: InstanceAlias): string

  /** Provider-default region if user didn't specify. */
  defaultRegion(): string

  /** State backend URL prefix for this provider. */
  stateBackendUrl(bucket: string): string

  /** Validate provider-specific config (env vars, profiles) at startup. */
  validateConfig(): Promise<ValidationResult>
}
