#!/usr/bin/env tsx
// scripts/gen-schemas.ts
// Generates src/providers/types.ts and src/mcp/tools/_generated.ts from spec/ files.
// Run: pnpm gen:schemas
// CI:  pnpm gen:schemas --check  (fails if committed files differ from generated output)

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'
import process from 'node:process'
import yaml from 'js-yaml'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const checkMode = process.argv.includes('--check')
let checkFailed = false

// ── helpers ───────────────────────────────────────────────────────────────────

function readJson(filePath: string): unknown {
  return JSON.parse(readFileSync(filePath, 'utf-8'))
}

function writeOrCheck(filePath: string, content: string): void {
  if (checkMode) {
    let existing: string
    try {
      existing = readFileSync(filePath, 'utf-8')
    } catch {
      console.error(`gen:schemas --check: ${filePath} does not exist. Run pnpm gen:schemas.`)
      checkFailed = true
      return
    }
    if (existing !== content) {
      console.error(
        `gen:schemas --check: ${filePath} is out of date. Run pnpm gen:schemas to regenerate.`,
      )
      checkFailed = true
    }
  } else {
    writeFileSync(filePath, content, 'utf-8')
    console.log(`  generated: ${filePath}`)
  }
}

function toUnion(values: string[]): string {
  return values.map(v => `'${v}'`).join(' | ')
}

// ── src/providers/types.ts ────────────────────────────────────────────────────

function genProviderTypes(): string {
  interface ProvidersSchema {
    properties: {
      name: { enum: string[] }
      credentials: { properties: { source: { enum: string[] } } }
      instanceTypes: { items: { properties: { alias: { enum: string[] } } } }
      stateBackend: { properties: { scheme: { enum: string[] } } }
    }
  }

  const schema = readJson(join(root, 'spec/providers.schema.json')) as ProvidersSchema
  const names = toUnion(schema.properties.name.enum)
  const credSources = toUnion(schema.properties.credentials.properties.source.enum)
  const aliases = toUnion(schema.properties.instanceTypes.items.properties.alias.enum)
  const stateSchemes = toUnion(schema.properties.stateBackend.properties.scheme.enum)

  return `// src/providers/types.ts — GENERATED. Do not hand-edit.
// Generated by: pnpm gen:schemas (scripts/gen-schemas.ts)
// Source of truth: spec/providers.schema.json

/** Inline Pulumi program — a closure that creates resources when called. */
export type PulumiFn = () => Promise<Record<string, unknown> | void>

/** Lowercase provider id matching the schema enum. */
export type ProviderName = ${names}

/** Normalised clawops instance-size alias. */
export type InstanceAlias = ${aliases}

/** How this provider's credentials are sourced (R6: never in tool args). */
export type CredentialSource = ${credSources}

/** Pulumi state backend URL scheme. */
export type StateBackendScheme = ${stateSchemes}

export interface ConnectionInfo {
  host: string
  port: number
  user: string
  privateKeyPath: string
  knownHostsPath: string
}

export interface BaseStackOutputs {
  instanceId: string
  publicIp: string
  gatewayUrl: string
  sshHost: string
  sshPort: number
  sshUser: string
  region: string
  /** ISO-8601 timestamp */
  provisionedAt: string
}

export type StackOutputs = BaseStackOutputs & Record<string, unknown>

export interface ValidationResult {
  ok: boolean
  errors: string[]
}

/** Contract every cloud provider adapter must satisfy. Per R-meta-1. */
export interface ProviderAdapter {
  /** Lowercase provider id matching the schema enum. */
  readonly name: ProviderName

  /** Inline Pulumi program for this provider's stack. */
  readonly program: PulumiFn

  /** Extract connection details from a deployed stack's outputs. */
  getConnectionInfo(outputs: StackOutputs): ConnectionInfo

  /** Map an alias like "small" to the provider's native instance type. */
  normalizeInstanceType(alias: InstanceAlias): string

  /** Provider-default region if user didn't specify. */
  defaultRegion(): string

  /** State backend URL prefix for this provider. */
  stateBackendUrl(bucket: string): string

  /** Validate provider-specific config (env vars, profiles) at startup. */
  validateConfig(): Promise<ValidationResult>
}
`
}

// ── src/mcp/tools/_generated.ts ───────────────────────────────────────────────

interface ToolInput {
  type: string
  optional?: boolean
  description?: string
  default?: unknown
  values?: string[]
  max?: number
  minimum?: number
  maximum?: number
}

interface Tool {
  name: string
  toolset: string | string[]
  description: string
  annotations: {
    title: string
    readOnlyHint: boolean
    destructiveHint: boolean
    idempotentHint: boolean
    openWorldHint: boolean
  }
  input?: Record<string, ToolInput>
}

interface McpSpec {
  version: number
  toolsets: Array<{ id: string; description: string }>
  tools: Tool[]
}

function toTypeName(toolName: string): string {
  // clawops_workflow_deploy_app → WorkflowDeployApp
  return toolName
    .replace(/^clawops_/, '')
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function zodField(key: string, def: ToolInput): string {
  let base: string

  if (def.type === 'enum' && def.values) {
    base = `z.enum([${def.values.map(v => `'${v}'`).join(', ')}])`
  } else if (def.type === 'integer') {
    base = 'z.number().int()'
  } else if (def.type === 'boolean') {
    base = 'z.boolean()'
  } else {
    base = 'z.string()'
  }

  if (def.default !== undefined) {
    // .optional().default(x) makes the field omittable in the inferred input type
    // while still guaranteeing the output is always the base type (never undefined).
    if (def.optional) {
      base += `.optional().default(${JSON.stringify(def.default)})`
    } else {
      base += `.default(${JSON.stringify(def.default)})`
    }
  } else if (def.optional) {
    base += '.optional()'
  }

  return `  ${key}: ${base},`
}

function genMcpTools(): string {
  const raw = readFileSync(join(root, 'spec/mcp-tools.yaml'), 'utf-8')
  const spec = yaml.load(raw) as McpSpec

  const toolsetsUnion = toUnion(spec.toolsets.map(ts => ts.id))

  const toolBlocks = spec.tools.map(tool => {
    const toolsets = Array.isArray(tool.toolset) ? tool.toolset : [tool.toolset]
    const fields = Object.entries(tool.input ?? {}).map(([k, v]) => zodField(k, v))
    const fieldsStr = fields.length ? '\n' + fields.join('\n') + '\n' : ''
    const typeName = toTypeName(tool.name)

    return [
      `// ── ${tool.name} ${'─'.repeat(Math.max(0, 72 - tool.name.length))}`,
      '',
      `export const ${tool.name}Schema = z.object({${fieldsStr}})`,
      '',
      `export const ${tool.name}Annotations = {`,
      `  title: ${JSON.stringify(tool.annotations.title)},`,
      `  readOnlyHint: ${tool.annotations.readOnlyHint},`,
      `  destructiveHint: ${tool.annotations.destructiveHint},`,
      `  idempotentHint: ${tool.annotations.idempotentHint},`,
      `  openWorldHint: ${tool.annotations.openWorldHint},`,
      `  toolsets: ${JSON.stringify(toolsets)} as const,`,
      '} as const',
      '',
      `export type ${typeName}Input = z.infer<typeof ${tool.name}Schema>`,
    ].join('\n')
  })

  // Build TOOLSETS registry
  const toolsetEntries = spec.toolsets.map(ts => {
    const tools = spec.tools.filter(t =>
      Array.isArray(t.toolset) ? t.toolset.includes(ts.id) : t.toolset === ts.id,
    )
    const entries = tools.map(t => `    '${t.name}',`).join('\n')
    return `  ${ts.id}: [\n${entries}\n  ],`
  })

  return [
    '// src/mcp/tools/_generated.ts — GENERATED. Do not hand-edit.',
    '// Generated by: pnpm gen:schemas (scripts/gen-schemas.ts)',
    '// Source of truth: spec/mcp-tools.yaml',
    '',
    "import { z } from 'zod'",
    '',
    `export type Toolset = ${toolsetsUnion}`,
    '',
    toolBlocks.join('\n\n'),
    '',
    '// ── TOOLSETS registry ─────────────────────────────────────────────────────────',
    '',
    'export const TOOLSETS: Record<Toolset, string[]> = {',
    toolsetEntries.join('\n'),
    '}',
    '',
  ].join('\n')
}

// ── main ──────────────────────────────────────────────────────────────────────

if (!checkMode) console.log('gen:schemas')

writeOrCheck(join(root, 'src/providers/types.ts'), genProviderTypes())
writeOrCheck(join(root, 'src/mcp/tools/_generated.ts'), genMcpTools())

if (checkMode) {
  if (checkFailed) {
    process.exit(1)
  } else {
    console.log('gen:schemas --check: all generated files are up to date')
  }
}
